### ISSUE TITLE
gulp --require doesn't work when running globally installed binary.

### ISSUE THREAD

**Issue by coreyfarrell** [gulpjs/gulp-cli#164]
I'm trying to use gulp with `esm` instead of babel as my project will only support new versions of node.js.  On my system I have gulp-cli@2.0.1 installed globally, gulp@next and esm installed locally.
Running the globally installed gulp:
```
$ gulp --require esm
[16:44:40] Requiring external module esm
/home/coreyfarrell/test/gulpfile.js:1
(function (exports, require, module, __filename, __dirname) { import log from 'gulplog';
                                                                     ^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```
Running the locally installed gulp:
```
$ npx gulp --require esm
[16:46:14] Requiring external module esm
[16:46:14] Using gulpfile ~/test/gulpfile.js
[16:46:14] Starting 'default'...
[16:46:14] Hello!
[16:46:14] Finished 'default' after 3.43 ms
```
My gulpfile.js:
```js
import log from 'gulplog';

export default () => {
	log.info('Hello!');
	return Promise.resolve();
};
```
gulp -v gives the same info global or local:
```
[16:49:35] CLI version 2.0.1
[16:49:35] Local version 4.0.0
```

**Comment by phated** [comment]
Esm claims it only works on local runs. Why/how would we do otherwise?

**Comment by coreyfarrell** [comment]
Hmm I guess I misunderstood how gulp-cli was expected to work.  I had thought that the global copy would run the local copy but it appears it doesn't actually spawn a new process in most cases.  Understanding esm is beyond me but I'm guessing 'local runs' means local to the actual process being run?  Anyways thanks for the reply I'll close this since it seems impractical to make it work as I hoped.

**Comment by phated** [comment]
@coreyfarrell I've actually been thinking about adding `esm` to the list of extensions in https://github.com/js-cli/js-interpret which might solve your issue.  I think we'd need the extension to be `.mjs` - is that correct?

If you want to open an issue over there, we might have a chance to add it.

**Comment by coreyfarrell** [comment]
`.mjs` is required by esm if the options mode == 'strict', not strictly required.  I think `.esm.mjs` should be used so it doesn't conflict with native .mjs in the future.

I created js-cli/js-interpret/issues/52.
