### ISSUE TITLE
Use of gulpfile.babel.js (ES6 import) with --gulpfile

### ISSUE THREAD

**Issue by dotherightthing** [gulpjs/gulp-cli#196]
I've renamed my `gulpfile.js` to `gulpfile.babel.js` to trigger the transpilation to ES5.

The Gulp tasks run as expected when I run `gulp` from the same directory:

```
[wpdtrt-generator-test-5] cd vendor/dotherightthing/wpdtrt-plugin-boilerplate                                                11:37:35
[wpdtrt-plugin-boilerplate] gulp lint                                                                                        11:38:32
[11:38:39] Requiring external module @babel/register
[11:38:52] Using gulpfile /Volumes/DanBackup/Websites/wpdtrt-generator-test-5/vendor/dotherightthing/wpdtrt-plugin-boilerplate/gulpfile.babel.js
[11:38:52] Starting 'lint'...
```

But they fail when I run the tasks from a parent directory:

```
[wpdtrt-generator-test-5] gulp lint --gulpfile ./vendor/dotherightthing/wpdtrt-plugin-boilerplate/gulpfile.babel.js --cwd ./ 11:29:55
[11:37:33] Requiring external module @babel/register
/Volumes/DanBackup/Websites/wpdtrt-generator-test-5/vendor/dotherightthing/wpdtrt-plugin-boilerplate/gulpfile.babel.js:12
import 'core-js/stable';
       ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._compile (/Volumes/DanBackup/Websites/wpdtrt-generator-test-5/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (/Volumes/DanBackup/Websites/wpdtrt-generator-test-5/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at execute (/Users/dan/.config/yarn/global/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
```

package.json (`/vendor/dotherightthing/wpdtrt-plugin-boilerplate/`):

```
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/preset-env": "^7.4.1",
    "@babel/register": "^7.5.5",
    "autoprefixer": "^9.6.1",
    "babel-eslint": "^10.0.3",
    "core-js": "^3.2.1",
    "del": "^5.1.0",
    "eslint": "^6.2.2",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-chai-friendly": "^0.4.1",
    "eslint-plugin-compat": "^3.3.0",
    "eslint-plugin-cypress": "^2.0.1",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-json": "^1.4.0",
    "eslint-plugin-markdown": "^1.0.0",
    "fancy-log": "^1.3.2",
    "gh-rate-limit": "^1.0.0",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-cli": "^2.2.0",
    "gulp-color": "^0.0.2",
    "gulp-download": "^0.0.1",
    "gulp-eslint": "^6.0.0",
    "gulp-phpcs": "^3.0.0",
    "gulp-postcss": "^8.0.0",
    "gulp-print": "^5.0.0",
    "gulp-rename": "^1.3.0",
    "gulp-replace": "^1.0.0",
    "gulp-sass": "^4.0.1",
    "gulp-sass-lint": "^1.4.0",
    "gulp-tap": "^2.0.0",
    "gulp-unzip": "^1.1.0",
    "gulp-wpdtrt-plugin-bump": "https://github.com/dotherightthing/gulp-wpdtrt-plugin-bump",
    "gulp-xmltojson": "^1.0.2",
    "gulp-zip": "^5.0.0",
    "include-media": "^1.4.9",
    "postcss-pxtorem": "^4.0.1",
    "regenerator-runtime": "^0.13.3",
    "sass-lint": "^1.12.1"
  },
```

.babelrc (`/vendor/dotherightthing/wpdtrt-plugin-boilerplate/`):

```
{
  "presets": [
    "@babel/env"
  ]
}
```

This setup was previously working, before I switched to ES6.

**Comment by sttk** [comment]
@dotherightthing Use babel's plugin: [@babel/helper-module-imports](https://babeljs.io/docs/en/next/babel-helper-module-imports.html)

**Comment by dotherightthing** [comment]
@sttk Sorry, I forgot to update this issue. I ended up creating an ES5 importer to import my ES6 `gulpfile.babel.js`.

https://github.com/dotherightthing/wpdtrt-plugin-boilerplate/blob/master/gulpfile-loader.js
