### ISSUE TITLE
YError: Invalid second argument. Expected string or boolean but received object.

### ISSUE THREAD

**Issue by shreyasch** [gulpjs/gulp-cli#235]
I updated yargs version in gulp-cli package.json file from ^7.0.1 to latest(17.4.1)
gulp-cli version- 2.3.0
yargs version - 17.4.1

Getting the following error

YError: Invalid second argument. Expected string or boolean but received object.
    at c (C:\...\node_modules\yargs\build\index.cjs:1:2244)
    at C:\...\node_modules\yargs\build\index.cjs:1:2096
    at Array.forEach (<anonymous>)
    at h (C:\...\node_modules\yargs\build\index.cjs:1:1993)
    at Xt.usage (C:\...\node_modules\yargs\build\index.cjs:1:42837)
    at Object.<anonymous> (C:\...\node_modules\gulp-cli\index.js:61:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
C:\...\node_modules\yargs\build\index.cjs:1
"use strict";var t=require("assert");class e extends Error{constructor(t){super(t||"yargs error"),...
...(rest of the file code)

e [YError]: .usage() description must start with $0 if being used as alias for .command()
    at Xt.usage (C:\...\node_modules\yargs\build\index.cjs:1:43041)
    at Object.<anonymous> (C:\...\node_modules\gulp-cli\index.js:61:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\...\node_modules\gulp\bin\gulp.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
	
	
Attaching the index.js file() code snippet  (gulp-cli/index.js)
at Object. (C:...\node_modules\gulp-cli\index.js:61:20)

<img width="795" alt="gulp-cli_index" src="https://user-images.githubusercontent.com/56544074/164992980-6f49b9e4-3654-4b02-8cea-ae8aabdab986.png">

**Comment by phated** [comment]
Seems like you tried upgrading yargs past a version we support.

**Comment by shreyasch** [comment]
Thanks for your reply @phated 

I tried the yargs version 11.0 and above in gulp-cli file but, got the same error message.
Yargs version 7.0.1 is showing vulnerable that's why I tried to upgrade it to the latest.

**Comment by shreyasch** [comment]
Is there any other way to resolve this error or any alternative solution that I can use?

**Comment by phated** [comment]
Nope. The yargs issue isn't relevant in normal gulp usage. Blindly upgrading dependencies across semver boundaries isn't wise.
