### ISSUE TITLE
Can't Run Coverage Tests

### ISSUE THREAD

**Issue by erikdonohoo** [gulpjs/gulp-cli#56]
Hey, locally I have modified the `coveralls` script to be `lab -r lcov >> lcov.info` just to see the coverage that it produces and everytime I see this error:

```javascript
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Task function must be specified
    at Gulp.set [as _setTask] (/Users/erikdonohoo/dev/personal/gulp-cli/node_modules/undertaker/lib/set-task.js:12:3)
    at Gulp.task (/Users/erikdonohoo/dev/personal/gulp-cli/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/erikdonohoo/dev/personal/gulp-cli/test/fixtures/gulpfile-3.8.10.js:9:6)
    at Module._compile (module.js:398:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/erikdonohoo/dev/personal/gulp-cli/node_modules/lab/lib/coverage.js:34:28)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/erikdonohoo/dev/personal/gulp-cli/node_modules/lab/lib/cli.js:104:23
    at Array.forEach (native)
    at Object.internals.traverse (/Users/erikdonohoo/dev/personal/gulp-cli/node_modules/lab/lib/cli.js:100:19)
    at Object.exports.run (/Users/erikdonohoo/dev/personal/gulp-cli/node_modules/lab/lib/cli.js:49:29)
    at Object.<anonymous> (/Users/erikdonohoo/dev/personal/gulp-cli/node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/erikdonohoo/.nvm/versions/node/v5.3.0/bin/node" "/Users/erikdonohoo/.nvm/versions/node/v5.3.0/bin/npm" "run" "coveralls"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! gulp-cli@1.1.0 coveralls: `lab -r lcov >> lcov.info`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gulp-cli@1.1.0 coveralls script 'lab -r lcov >> lcov.info'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gulp-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lab -r lcov >> lcov.info
npm ERR! You can get their info via:
npm ERR!     npm owner ls gulp-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/erikdonohoo/dev/personal/gulp-cli/npm-debug.log
```

Is there something I am missing here?  I am looking at your code as an example of how to test a node CLI tool.  I'm reading up and `lab` and `code` but do you have any ideas just by looking at this?  I am using `nvm` on my machine for my node install.  It seems like `lab` is trying to cover files it shouldn't.  Is there a way to tell lab which files are meant to be run?

**Comment by phated** [comment]
You can't get coverage out of the current tests we have.  We use `child_process.exec` to shell out to CLI calls.  I wouldn't use the way this library is tested as an example for how to write CLI tests, but I also don't have any other suggestions.

**Comment by erikdonohoo** [comment]
Ok, thanks anyway
